apiVersion: v1
kind: Secret
metadata: { name: bank-shared-secret, namespace: bank-usac }
type: Opaque
stringData:
  JWT_SECRET: bank-usac-demo-secret-change-before-production-2026
  RABBITMQ_URL: amqp://rabbit_user:rabbit_password@rabbitmq:5672
