services:
  notification-audit-service:
    build:
      context: ../apps/notification-audit-service
      dockerfile: Dockerfile
    container_name: notification-audit-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      DB_HOST: notification-db
      DB_PORT: 5432
      DB_DATABASE: bank_notification
      DB_USERNAME: notification_user
      DB_PASSWORD: notification_password
      DB_SCHEMA: public
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_password
    depends_on:
      notification-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - bank-net
