spring:
  datasource:
    url: jdbc:postgresql://${NOTIF_DB_HOST:${DB_HOST:localhost}}:${NOTIF_DB_PORT:${DB_PORT:5435}}/${NOTIF_DB_NAME:${DB_DATABASE:bank_notification}}
    username: ${NOTIF_DB_USER:${DB_USERNAME:notification_user}}
    password: ${NOTIF_DB_PASSWORD:${DB_PASSWORD:notification_password}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:rabbit_user}
    password: ${RABBITMQ_DEFAULT_PASS:rabbit_password}
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_FROM:no-reply@bankusac.local}
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
server:
  port: 8082
management:
  endpoints.web.exposure.include: health,info,metrics
bank:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
