apiVersion: apps/v1
kind: Deployment
metadata: { name: account-service, namespace: bank-usac }
spec:
  replicas: 1
  selector: { matchLabels: { app: account-service } }
  template:
    metadata: { labels: { app: account-service } }
    spec:
      containers:
        - name: account-service
          image: bank-usac/account-service:local
          imagePullPolicy: IfNotPresent
          ports: [{containerPort: 3004}]
          env:
            - { name: PORT, value: "3004" }
            - { name: DB_HOST, valueFrom: { configMapKeyRef: { name: bank-db-config, key: ACCOUNT_DB_HOST } } }
            - { name: DB_PORT, valueFrom: { configMapKeyRef: { name: bank-db-config, key: ACCOUNT_DB_PORT } } }
            - { name: DB_DATABASE, valueFrom: { configMapKeyRef: { name: bank-db-config, key: ACCOUNT_DB_NAME } } }
            - { name: DB_USERNAME, valueFrom: { secretKeyRef: { name: bank-db-secret, key: ACCOUNT_DB_USER } } }
            - { name: DB_PASSWORD, valueFrom: { secretKeyRef: { name: bank-db-secret, key: ACCOUNT_DB_PASSWORD } } }
            - { name: DB_SYNCHRONIZE, value: "true" }
            - { name: RABBITMQ_URL, valueFrom: { secretKeyRef: { name: bank-shared-secret, key: RABBITMQ_URL } } }
            - { name: RABBITMQ_QUEUE, value: "account-service.events" }
          readinessProbe: { httpGet: { path: /health, port: 3004 }, initialDelaySeconds: 5, periodSeconds: 5 }
          livenessProbe: { httpGet: { path: /health, port: 3004 }, periodSeconds: 10, failureThreshold: 3 }
          # Hasta 150 s para arrancar (espera a RabbitMQ y la DB); mientras tanto no corre la liveness.
          startupProbe: { httpGet: { path: /health, port: 3004 }, periodSeconds: 5, failureThreshold: 30 }
---
apiVersion: v1
kind: Service
metadata: { name: account-service, namespace: bank-usac }
spec: { selector: { app: account-service }, ports: [{port: 3004,targetPort: 3004}] }
