apiVersion: apps/v1
kind: Deployment
metadata: { name: payment-service, namespace: bank-usac }
spec:
  replicas: 1
  selector: { matchLabels: { app: payment-service } }
  template:
    metadata: { labels: { app: payment-service } }
    spec:
      containers:
        - name: payment-service
          image: bank-usac/payment-service:local
          imagePullPolicy: IfNotPresent
          ports: [{containerPort: 3005}]
          env:
            - { name: PORT, value: "3005" }
            - { name: DB_HOST, valueFrom: { configMapKeyRef: { name: bank-db-config, key: PAYMENT_DB_HOST } } }
            - { name: DB_PORT, valueFrom: { configMapKeyRef: { name: bank-db-config, key: PAYMENT_DB_PORT } } }
            - { name: DB_DATABASE, valueFrom: { configMapKeyRef: { name: bank-db-config, key: PAYMENT_DB_NAME } } }
            - { name: DB_USERNAME, valueFrom: { secretKeyRef: { name: bank-db-secret, key: PAYMENT_DB_USER } } }
            - { name: DB_PASSWORD, valueFrom: { secretKeyRef: { name: bank-db-secret, key: PAYMENT_DB_PASSWORD } } }
            - { name: DB_SYNCHRONIZE, value: "true" }
            - { name: RABBITMQ_URL, valueFrom: { secretKeyRef: { name: bank-shared-secret, key: RABBITMQ_URL } } }
            - { name: RABBITMQ_QUEUE, value: "payment-service.events" }
            - { name: PAYMENT_MAX_AMOUNT, value: "1000000" }
          readinessProbe: { httpGet: { path: /health, port: 3005 }, initialDelaySeconds: 5, periodSeconds: 5 }
          livenessProbe: { httpGet: { path: /health, port: 3005 }, periodSeconds: 10, failureThreshold: 3 }
          # Hasta 150 s para arrancar (espera a RabbitMQ y la DB); mientras tanto no corre la liveness.
          startupProbe: { httpGet: { path: /health, port: 3005 }, periodSeconds: 5, failureThreshold: 30 }
---
apiVersion: v1
kind: Service
metadata: { name: payment-service, namespace: bank-usac }
spec: { selector: { app: payment-service }, ports: [{port: 3005,targetPort: 3005}] }
